In [1]:
from torch_geometric.datasets import Planetoid,Amazon
import os 
from dotenv import load_dotenv
from torch_geometric.nn import global_max_pool, global_mean_pool
from torch_geometric.utils import dropout_node
from torch.nn import Module
import torch
from dotenv import load_dotenv


In [2]:
load_dotenv('.env')

True

In [4]:
cora_path=os.getenv('CiteSeer')
graph = Planetoid(root=cora_path, name='CiteSeer')

In [5]:
edge_index, _, node_mask = dropout_node(graph.edge_index)

In [6]:
node_mask.size()

torch.Size([3327])

In [7]:
graph.x.size()

torch.Size([3327, 3703])

In [8]:
graph.x[2707][1328]

tensor(0.)

In [9]:
torch.where(graph.x==1)

(tensor([   0,    0,    0,  ..., 3326, 3326, 3326]),
 tensor([ 184,  257,  362,  ..., 3472, 3556, 3621]))

In [10]:
torch.unique(graph.x)

tensor([0., 1.])

In [11]:
u=node_mask.int().unsqueeze(1)*graph.x

In [12]:
torch.where(node_mask==True)

(tensor([   0,    5,   10,  ..., 3317, 3321, 3326]),)

In [ ]:
u

In [16]:
u[3326][3621]


tensor(1.)